"""
Django settings for server_tfg project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/

!!!!ASPEL!!!!
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0(bs-i=haq$)jt=#jz6hennj3qst1z4ie7$)ldxvxz&$_1f&n('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.48','localhost','10.1.140.203']


# Application definition

INSTALLED_APPS = (
    'serverapps',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'server_tfg.urls'



WSGI_APPLICATION = 'server_tfg.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

TEMPLATE_DIRS = ('templates/',)
API_MONGO_DIR = '/home/jorge/tfg/connect_python_to_mongo/'
HOST_MONGO = 'localhost'
PORT_MONGO = 27017
FILES_PATIENT_UPLOAD = '/home/jorge/tfg/uploaded_files'
API_STATISTICS_DIR = '/home/jorge/tfg/statistics_functions/'
DISEASES_TXT = '/home/jorge/tfg/diseases.txt'
MEDICINES_TXT = '/home/jorge/tfg/medicines.txt'

STATIC_URL = '/static/'
STATIC_URL_CSS = 'templates/css/'
STATIC_URL_JS = 'templates/js/'
STATIC_URL_IMAGES = 'templates/images/'

MEDIA_ROOT = '/home/jorge/tfg/uploaded_files'
